# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c6236c49-3465-4de2-9208-4432b27cf3a9";
      fsType = "btrfs";
      options = [ "subvol=NixOS/@" ];
    };

  boot.initrd.luks.devices."ssd_crypt".device = "/dev/disk/by-uuid/a39302ef-abb4-464e-8fa1-fc332f8102e0";

  fileSystems."/etc/nixos" =
    { device = "/dev/disk/by-uuid/c6236c49-3465-4de2-9208-4432b27cf3a9";
      fsType = "btrfs";
      options = [ "subvol=NixOS/@etc@nixos" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c6236c49-3465-4de2-9208-4432b27cf3a9";
      fsType = "btrfs";
      options = [ "subvol=NixOS/@home" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/E881-1C4F";
      fsType = "vfat";
    };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
