# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e363e774-4238-45ac-94b7-691623bf27b9";
      fsType = "btrfs";
      options = [ "subvol=NixOS/@" ];
    };

  boot.initrd.luks.devices."sda2_crypt".device = "/dev/disk/by-uuid/8aedd2c2-2518-49fd-8d14-d22a64804fc1";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/e363e774-4238-45ac-94b7-691623bf27b9";
      fsType = "btrfs";
      options = [ "subvol=NixOS/@home" ];
    };

  fileSystems."/etc/nixos" =
    { device = "/dev/disk/by-uuid/e363e774-4238-45ac-94b7-691623bf27b9";
      fsType = "btrfs";
      options = [ "subvol=NixOS/@etc@nixos" ];
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/AC26-5FEB";
      fsType = "vfat";
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/e363e774-4238-45ac-94b7-691623bf27b9";
      fsType = "btrfs";
      options = [ "subvol=NixOS/@swap" ];
    };

  swapDevices = [ ];

}
