# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = ["ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/c3e27699-ec88-4863-9891-588c59c3642f";
    fsType = "btrfs";
    options = ["subvol=NixOS/@"];
  };

  boot.initrd.luks.devices."sda3_crypt".device = "/dev/disk/by-uuid/b2953919-8d01-4b8a-9ceb-e37a81de12c2";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/289a0d49-17e8-4a89-89d8-3664dfd59d42";
    fsType = "ext4";
  };

  fileSystems."/etc/nixos" = {
    device = "/dev/disk/by-uuid/c3e27699-ec88-4863-9891-588c59c3642f";
    fsType = "btrfs";
    options = ["subvol=NixOS/@etc@nixos"];
  };

  fileSystems."/etc/secrets" = {
    device = "/dev/disk/by-uuid/c3e27699-ec88-4863-9891-588c59c3642f";
    fsType = "btrfs";
    options = ["subvol=NixOS/@etc@secrets"];
  };

  fileSystems."/srv" = {
    device = "/dev/disk/by-uuid/c3e27699-ec88-4863-9891-588c59c3642f";
    fsType = "btrfs";
    options = ["subvol=NixOS/@srv"];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/c3e27699-ec88-4863-9891-588c59c3642f";
    fsType = "btrfs";
    options = ["subvol=NixOS/@swap"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/c3e27699-ec88-4863-9891-588c59c3642f";
    fsType = "btrfs";
    options = ["subvol=NixOS/@home"];
  };

  swapDevices = [];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
