# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "uas" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/fsroot_crypt";
    fsType = "btrfs";
    options = ["subvol=NixOS/@"];
  };

  boot.initrd.luks.devices."fsroot_crypt".device = "/dev/disk/by-uuid/ef3dc0c1-1715-4844-b9b1-61c74f44ff61";

  fileSystems."/home" = {
    device = "/dev/mapper/fsroot_crypt";
    fsType = "btrfs";
    options = ["subvol=NixOS/@home"];
  };

  fileSystems."/etc/nixos" = {
    device = "/dev/mapper/fsroot_crypt";
    fsType = "btrfs";
    options = ["subvol=NixOS/@etc@nixos"];
  };

  fileSystems."/etc/secrets" = {
    device = "/dev/mapper/fsroot_crypt";
    fsType = "btrfs";
    options = ["subvol=NixOS/@etc@secrets"];
  };

  fileSystems."/swap" = {
    device = "/dev/mapper/fsroot_crypt";
    fsType = "btrfs";
    options = ["subvol=NixOS/@swap"];
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/D463-22A2";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
